//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDostava_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnik()
        {
            this.LoginStats = new HashSet<LoginStats>();
        }
    
        public int KorisnikID { get; set; }
        public string Username { get; set; }
        public string LozinkaHash { get; set; }
        public string LozinkaSalt { get; set; }
        public string Email { get; set; }
        public System.DateTime DatumRegistracije { get; set; }
    
        public virtual Administratori Administratori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginStats> LoginStats { get; set; }
        public virtual Narucioci Narucioci { get; set; }
        public virtual Vlasnici Vlasnici { get; set; }
        public virtual Zaposlenici Zaposlenici { get; set; }
    }
}
