//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDostava_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginStats
    {
        public int LoginStatID { get; set; }
        public int KorisnikID { get; set; }
        public System.DateTime DatumLogiranja { get; set; }
        public System.TimeSpan TrajanjeSesije { get; set; }
        public string Ip { get; set; }
        public string UserAgent { get; set; }
        public string FirstAction { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
