//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDostava_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recenzije
    {
        public int RestoranRecenzijaID { get; set; }
        public Nullable<int> NarucilacID { get; set; }
        public int RestoranID { get; set; }
        public System.DateTime Datum { get; set; }
        public string Komentar { get; set; }
        public int Ocjena { get; set; }
    
        public virtual Narucioci Narucioci { get; set; }
        public virtual Restorani Restorani { get; set; }
    }
}
