//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDostava_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restorani
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restorani()
        {
            this.Hrana = new HashSet<Hrana>();
            this.Recenzije = new HashSet<Recenzije>();
            this.Zalbe = new HashSet<Zalbe>();
            this.Vlasnici = new HashSet<Vlasnici>();
            this.Zaposlenici = new HashSet<Zaposlenici>();
        }
    
        public int RestoranID { get; set; }
        public System.Guid Sifra { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Email { get; set; }
        public string WebUrl { get; set; }
        public string Telefon { get; set; }
        public Nullable<decimal> MinimalnaCijenaNarudzbe { get; set; }
        public int KorisnikID { get; set; }
        public string Adresa { get; set; }
        public int BlokID { get; set; }
        public byte[] Slika { get; set; }
        public Nullable<int> RestoranStatusID { get; set; }
    
        public virtual Blokovi Blokovi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hrana> Hrana { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recenzije> Recenzije { get; set; }
        public virtual RestoranStatusi RestoranStatusi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zalbe> Zalbe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vlasnici> Vlasnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaposlenici> Zaposlenici { get; set; }
    }
}
