//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDostava_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposlenici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zaposlenici()
        {
            this.Narudzbe = new HashSet<Narudzbe>();
        }
    
        public int KorisnikID { get; set; }
        public System.Guid Sifra { get; set; }
        public int RestoranID { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Restorani Restorani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzbe> Narudzbe { get; set; }
    }
}
