//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRestoraniUI.ResourceMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eRestoraniUI.ResourceMessages.ApiMessages", typeof(ApiMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prije promjene provjerite podatke koji ovise o ovoj!.
        /// </summary>
        internal static string delexc_503 {
            get {
                return ResourceManager.GetString("delexc_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokušajte prvo izbrisati zapise koji ovise o ovom!.
        /// </summary>
        internal static string sqlexception_547 {
            get {
                return ResourceManager.GetString("sqlexception_547", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemoguće izbrisati blok jer postoje restorani s istim!.
        /// </summary>
        internal static string sqlexception_547_blok {
            get {
                return ResourceManager.GetString("sqlexception_547_blok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate prvo izbrisati sve blokove koji pripadaju ovom gradu!.
        /// </summary>
        internal static string sqlexception_547_grad {
            get {
                return ResourceManager.GetString("sqlexception_547_grad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemoguće izbrisati restoran jer postoje korisnički računi i drugi podaci koji ovise o njemu!.
        /// </summary>
        internal static string sqlexception_547_restoran {
            get {
                return ResourceManager.GetString("sqlexception_547_restoran", resourceCulture);
            }
        }
    }
}
