//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRestoraniUI.ResourceMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eRestoraniUI.ResourceMessages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je u pogrešnom formatu.
        /// </summary>
        internal static string email_format_error {
            get {
                return ResourceManager.GetString("email_format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje Email ne smije biti prazno.
        /// </summary>
        internal static string email_required_error {
            get {
                return ResourceManager.GetString("email_required_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške, molimo pokušajte ponovo ili izaberite postojeći {0}..
        /// </summary>
        internal static string greska_msg_obj_body {
            get {
                return ResourceManager.GetString("greska_msg_obj_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške, pokušajte ponovo..
        /// </summary>
        internal static string greska_msg_pokusaj_ponovo {
            get {
                return ResourceManager.GetString("greska_msg_pokusaj_ponovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        internal static string greska_msg_title {
            get {
                return ResourceManager.GetString("greska_msg_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni da želite izbrisati {0}?.
        /// </summary>
        internal static string izbrisi_obj_potvrda {
            get {
                return ResourceManager.GetString("izbrisi_obj_potvrda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbriši {0}.
        /// </summary>
        internal static string izbrisi_obj_potvrda_title {
            get {
                return ResourceManager.GetString("izbrisi_obj_potvrda_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste pogrešno korisničko ime ili lozinku.
        /// </summary>
        internal static string login_user_invalid_credentials {
            get {
                return ResourceManager.GetString("login_user_invalid_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje username ili password ne smiju biti kraći od 4 karaktera!.
        /// </summary>
        internal static string login_user_invalid_length {
            get {
                return ResourceManager.GetString("login_user_invalid_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate odabrati {0}!.
        /// </summary>
        internal static string morate_odabrati_msg_obj {
            get {
                return ResourceManager.GetString("morate_odabrati_msg_obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite zapis.
        /// </summary>
        internal static string morate_odabrati_title {
            get {
                return ResourceManager.GetString("morate_odabrati_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narudžbe naručioca: {0}.
        /// </summary>
        internal static string narudzbe_narucioca {
            get {
                return ResourceManager.GetString("narudzbe_narucioca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narudžbe restorana: {0}.
        /// </summary>
        internal static string narudzbe_restorana {
            get {
                return ResourceManager.GetString("narudzbe_restorana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje Naziv ne smije biti prazno.
        /// </summary>
        internal static string naziv_obavezno_polje {
            get {
                return ResourceManager.GetString("naziv_obavezno_polje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneseni {0} ne postoji u bazi podataka, želite kreirati novi pod nazivom &quot;{1}&quot;?.
        /// </summary>
        internal static string obj_ne_postoji_kreiraj_novi_msg {
            get {
                return ResourceManager.GetString("obj_ne_postoji_kreiraj_novi_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi tip {0}.
        /// </summary>
        internal static string obj_ne_postoji_kreiraj_novi_title {
            get {
                return ResourceManager.GetString("obj_ne_postoji_kreiraj_novi_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje {0} smije sadržati samo {1}!.
        /// </summary>
        internal static string polje_type_error {
            get {
                return ResourceManager.GetString("polje_type_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje {0} smije sadržati samo {1} i ne smije biti kraće od {2}, ili duže od {3} karaktera!.
        /// </summary>
        internal static string polje_type_length_error {
            get {
                return ResourceManager.GetString("polje_type_length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika je prevelika za upload, molimo izaberite neku manju!.
        /// </summary>
        internal static string slika_out_of_mem {
            get {
                return ResourceManager.GetString("slika_out_of_mem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutni status: {0}.
        /// </summary>
        internal static string trenutni_status {
            get {
                return ResourceManager.GetString("trenutni_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutni status restorana {0}.
        /// </summary>
        internal static string trenutni_status_restoran {
            get {
                return ResourceManager.GetString("trenutni_status_restoran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno {0}.
        /// </summary>
        internal static string ukupno_general {
            get {
                return ResourceManager.GetString("ukupno_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno {0}: {1}.
        /// </summary>
        internal static string ukupno_sta_koliko {
            get {
                return ResourceManager.GetString("ukupno_sta_koliko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno {0}: {1}.
        /// </summary>
        internal static string ukupno_type_number {
            get {
                return ResourceManager.GetString("ukupno_type_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za korisnika &quot;{0}&quot;, nakon prebacivanja u grupu &quot;{1}&quot;, moraćete definisati restoran!.
        /// </summary>
        internal static string uloge_izmjene_napomene_def_restoran {
            get {
                return ResourceManager.GetString("uloge_izmjene_napomene_def_restoran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik &quot;{0}&quot; prebačen u ulogu/grupu &quot;{1}&quot;.
        /// </summary>
        internal static string uloge_izmjene_pregled {
            get {
                return ResourceManager.GetString("uloge_izmjene_pregled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi restoran - {0}.
        /// </summary>
        internal static string uredi_restoran_obj {
            get {
                return ResourceManager.GetString("uredi_restoran_obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izbrisali {0}!.
        /// </summary>
        internal static string uspjeh_delete_obj {
            get {
                return ResourceManager.GetString("uspjeh_delete_obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis izbrisan.
        /// </summary>
        internal static string uspjeh_delete_title {
            get {
                return ResourceManager.GetString("uspjeh_delete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste snimili {0}!.
        /// </summary>
        internal static string uspjeh_save_obj {
            get {
                return ResourceManager.GetString("uspjeh_save_obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjeh.
        /// </summary>
        internal static string uspjeh_save_title {
            get {
                return ResourceManager.GetString("uspjeh_save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjeh.
        /// </summary>
        internal static string uspjeh_title {
            get {
                return ResourceManager.GetString("uspjeh_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste sačuvali izmjene!.
        /// </summary>
        internal static string uspjesno_napravljene_izmjene_body {
            get {
                return ResourceManager.GetString("uspjesno_napravljene_izmjene_body", resourceCulture);
            }
        }
    }
}
