//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRestoraniUI.ResourceMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eRestoraniUI.ResourceMessages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je u pogrešnom formatu.
        /// </summary>
        internal static string edit_restoran_email_format_error {
            get {
                return ResourceManager.GetString("edit_restoran_email_format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje Email ne smije biti prazno.
        /// </summary>
        internal static string edit_restoran_obavezno_polje_email {
            get {
                return ResourceManager.GetString("edit_restoran_obavezno_polje_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje Naziv ne smije biti prazno.
        /// </summary>
        internal static string edit_restoran_obavezno_polje_naziv {
            get {
                return ResourceManager.GetString("edit_restoran_obavezno_polje_naziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno {0}: {1}.
        /// </summary>
        internal static string grid_ukupno_stavki {
            get {
                return ResourceManager.GetString("grid_ukupno_stavki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste pogrešno korisničko ime ili lozinku.
        /// </summary>
        internal static string login_user_fail {
            get {
                return ResourceManager.GetString("login_user_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narudžbe naručioca: {0}.
        /// </summary>
        internal static string narudzbe_narucioca {
            get {
                return ResourceManager.GetString("narudzbe_narucioca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narudžbe restorana: {0}.
        /// </summary>
        internal static string narudzbe_restorana {
            get {
                return ResourceManager.GetString("narudzbe_restorana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutni status restorana {0}.
        /// </summary>
        internal static string restoran_trenutni_status {
            get {
                return ResourceManager.GetString("restoran_trenutni_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno {0}.
        /// </summary>
        internal static string ukupno_general {
            get {
                return ResourceManager.GetString("ukupno_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno {0}: {1}.
        /// </summary>
        internal static string ukupno_sta_koliko {
            get {
                return ResourceManager.GetString("ukupno_sta_koliko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za korisnika &quot;{0}&quot;, nakon prebacivanja u grupu &quot;{1}&quot;, moraćete definisati restoran!.
        /// </summary>
        internal static string uloge_izmjene_napomene_def_restoran {
            get {
                return ResourceManager.GetString("uloge_izmjene_napomene_def_restoran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik &quot;{0}&quot; prebačen u ulogu/grupu &quot;{1}&quot;.
        /// </summary>
        internal static string uloge_izmjene_pregled {
            get {
                return ResourceManager.GetString("uloge_izmjene_pregled", resourceCulture);
            }
        }
    }
}
