//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRestoraniUI.ResourceMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eRestoraniUI.ResourceMessages.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške, molimo pokušajte ponovo ili izaberite postojeći {0}..
        /// </summary>
        internal static string GreskaKreiranObj {
            get {
                return ResourceManager.GetString("GreskaKreiranObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        internal static string GreskaKreiranTitle {
            get {
                return ResourceManager.GetString("GreskaKreiranTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške, pokušajte ponovo..
        /// </summary>
        internal static string GreskaPokusajPonovo {
            get {
                return ResourceManager.GetString("GreskaPokusajPonovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni da želite izbrisati &quot;{0}&quot;?.
        /// </summary>
        internal static string IzbrisiStavkuPotvrda {
            get {
                return ResourceManager.GetString("IzbrisiStavkuPotvrda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbriši {0}.
        /// </summary>
        internal static string IzbrisiStavkuTitle {
            get {
                return ResourceManager.GetString("IzbrisiStavkuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneseni {0} ne postoji u bazi podataka, želite kreirati novi pod nazivom &quot;{1}&quot;?.
        /// </summary>
        internal static string ObjNePostojiKreirajNovi {
            get {
                return ResourceManager.GetString("ObjNePostojiKreirajNovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi tip {0}.
        /// </summary>
        internal static string ObjNePostojiKreirajNoviTitle {
            get {
                return ResourceManager.GetString("ObjNePostojiKreirajNoviTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje {0} smije sadržati samo {1}!.
        /// </summary>
        internal static string polje_tip {
            get {
                return ResourceManager.GetString("polje_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje {0} smije sadržati samo {1} i ne smije biti kraće od {2}, ili duže od {3} karaktera!.
        /// </summary>
        internal static string polje_tip_duzina {
            get {
                return ResourceManager.GetString("polje_tip_duzina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate odabrati {0}!.
        /// </summary>
        internal static string PrvoIzaberiObj {
            get {
                return ResourceManager.GetString("PrvoIzaberiObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjeh.
        /// </summary>
        internal static string UspjenoKreiranTitle {
            get {
                return ResourceManager.GetString("UspjenoKreiranTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izbrisali {0}!.
        /// </summary>
        internal static string UspjesnoIzbrisanObj {
            get {
                return ResourceManager.GetString("UspjesnoIzbrisanObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis izbrisan.
        /// </summary>
        internal static string UspjesnoIzbrisanTitle {
            get {
                return ResourceManager.GetString("UspjesnoIzbrisanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste snimili {0}!.
        /// </summary>
        internal static string UspjesnoKreiranObj {
            get {
                return ResourceManager.GetString("UspjesnoKreiranObj", resourceCulture);
            }
        }
    }
}
